### ISSUE TITLE
Better SNV caller than samtools

### ISSUE THREAD

**Issue by dnil** [kristinebilgrav/LOMPE#3]
Samtools is nice and easy to understand the details - thats where we started, so all good , but there are methods with better sensitivity and specificity. E.g. DeepVariant has an ONT version, which could be easymode for downstream stuff, as we already use DeepVariant for Illumina SR. Presumably also the native and semi native options like Megalodon would rival samtools?

**Comment by kristinebilgrav** [comment]
Deppvariant supported
